### ISSUE TITLE
Failed to build flexvolume plugin

### ISSUE THREAD

**Issue by cuericlee** [AliyunContainerService/flexvolume#1]
When I tried to compile this disk project, I saw missing dependencies, gitlab.alibaba-inc.com/acs/flexvolume. Can you direct me how external user reach these dependency libs and make build work?

provider/alicloud/disk.go:13:2: cannot find package "gitlab.alibaba-inc.com/acs/flexvolume" in any of:

root@iZm5ei1y1msv4m05vlcfbhZ:~/projects/goprojects/src/github.com/AliyunContainerService/alicloud-controller-manager# export REGISTRY=registry.cn-hangzhou.aliyuncs.com/google-containers
root@iZm5ei1y1msv4m05vlcfbhZ:~/projects/goprojects/src/github.com/AliyunContainerService/alicloud-controller-manager# make all
rm -f alicloud-controller-manager
GOOS=linux go build -o alicloud-controller-manager

**Comment by XdaTk** [comment]
试试替换：https://github.com/AliyunContainerService/flexvolume

**Comment by cuericlee** [comment]
it works, can you grant me as contributor, then I could submit a PR accordingly.
