### ISSUE TITLE
通过config文件配置kubelet的情况下误判enable-controller-attach-detach没有设置

### ISSUE THREAD

**Issue by leostudio** [AliyunContainerService/flexvolume#10]
k8s 1.10+支持通过cofig file配置kubelet参数（https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/），如果在此文件中配置enable-controller-attach-detach: false，那么entrypoint.sh中还是通过ps -ef获取参数的方式判断，则会误判，kubelet没有以enable-controller-attach-detach=false的方式启动。

**Comment by xlgao-zju** [comment]
@fredkan Should we change the `entrypoint.sh`?

/assign @fredkan

**Comment by fredkan** [comment]
Yes, this should be considered in next release.

**Comment by silenceper** [comment]
请问下 `enable-controller-attach-detach`参数的作用是什么，必须设置为flase 才能使用flexvolume吗？

**Comment by fredkan** [comment]
k8s中两个地方可以做attach操作：
1. 配置为true，使用master组件中的ADController实现attach：操作在master节点完成；
2. 配置为false，使用kubelet中volume manager驱动，本项目中的实现：操作在相应节点完成；

由于云盘目前的实现方式，只能使用相应节点挂载，所以需要把这配置为false；

**Comment by fredkan** [comment]
fixed
