### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by ermazi** [AliyunContainerService/flexvolume#11]
现在出现个问题，节点失联，然后删除pvc后，然后节点回来了，节点携带着N块盘，这时候这几块盘处于released状态，然后通过k8s删掉这几个pv，并不能删除阿里云的disk实例，导致磁盘侧漏。
请问阿里云在这个问题是怎么解决的呢？

**Comment by ermazi** [comment]
也许我不该在这里问这个问题，这只是个flexvolume插件，扫描pv状态的过程不在这里。

**Comment by kaiterramike** [comment]
这是因为这个flexvolume driver 不支持[dynamic provisioning](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/)。所以，当你需要新的pv时，你要在阿里云console里手动地添加disk实列；然后删除pvc之后硬盘处于released状态，你还需要手动地删除disk实列。

如果你需要dynamic provisioning的话，去看https://github.com/kubeup/kube-aliyun。

**Comment by fredkan** [comment]
谢谢@originsmike ；
@ermazi 目前阿里云容器服务的dynamic provisioner已经开源：https://github.com/AliyunContainerService/alicloud-storage-provisioner

通过配置storageclass的reclaim为Delete类型，可以在删除PVC的同时一起删除后端的云盘实例；
