### ISSUE TITLE
disk 为什么不支持mount

### ISSUE THREAD

**Issue by silenceper** [AliyunContainerService/flexvolume#13]
https://github.com/AliyunContainerService/flexvolume/blob/57ffadebb015b227ed8ff6211e163995dd119f6e/provider/disk/disk.go#L243-L245

看到这里disk 是not  support  ，那在attach主机之后，是在哪里做这个动作？

**Comment by fredkan** [comment]
> [flexvolume/provider/disk/disk.go](https://github.com/AliyunContainerService/flexvolume/blob/57ffadebb015b227ed8ff6211e163995dd119f6e/provider/disk/disk.go#L243-L245)
> 
> Lines 243 to 245 in [57ffade](/AliyunContainerService/flexvolume/commit/57ffadebb015b227ed8ff6211e163995dd119f6e)
> 
>  func (p *DiskPlugin) Mount(opts interface{}, mountPath string) utils.Result { 
>  	return utils.NotSupport() 
>  } 
> 看到这里disk 是not support ，那在attach主机之后，是在哪里做这个动作？

mount is executed as flexvolume default mount.
