### ISSUE TITLE
[nas]noresvport挂载参数问题

### ISSUE THREAD

**Issue by zeusro** [AliyunContainerService/flexvolume#15]
今天刚收到一个通知:

> 阿里云NAS文件存储后台扫描发现，您的NFS文件系统没有使用noresvport参数挂载，存在严重的可用性风险。
> 
> 某些场景下的网络切换或后端服务的HA倒换，都可能造成您的业务长时间阻塞，无法自动恢复。此风险时刻威胁您的业务正常运行，请尽快处理。
> 
> 请确保您的ECS内核版本满足要求，并且确认noresvport挂载参数生效，规避该风险。详细的判断标准和处理步骤，请参考帮助文档https://c.tb.cn/a.cAQOl
> 
> 具体存在风险的ECS和挂载的NFS文件系统列表如下，格式为“ECS内网IP地址：NFS文件系统列表”

受风险影响的主机包括所有的kubernetes节点.我想了一下,动态PVC的挂载是通过flexvolume实现的,我去修复这个问题没有用.得你们更新一下flexvolume docker镜像,并提示用户修复才对.

**Comment by fredkan** [comment]
此问题正在验证方案，很快会给出。

**Comment by mumutu66** [comment]
flexvolume代码看起来是有的 可能取决于alicloud-nas-controller的配置

**Comment by fredkan** [comment]
https://yq.aliyun.com/articles/707169?spm=a2c4e.11155435.0.0.41033312hwsv3v
