### ISSUE TITLE
flexvolume alicloud-disk 插件问题咨询

### ISSUE THREAD

**Issue by ideapark** [AliyunContainerService/flexvolume#17]
【环境】
1. aliyun ecs 11 nodes
2. openshift 3.11 (kubernetes 1.11 的一个发行版)

【部署阿里存储插件】
1. alicloud-disk-controller
2. flexvolume

【操作】
1. 动态申请了一个pv 20G, StorageClass: alicloud-disk-efficiency， Mode：RWO
2. 启动了一个 Pod 声明 pvc 并且绑定到了 pv
3. Pod 运行正常，存储挂正常，数据读写正常

【触发异常操作】
1. 将 Pod replicas 改为 2
2. 第二个 Pod 被 k8s 调度并且启动成功 （BUG：Pod pvc挂载应该失败，Pod 应该 Pending）

【问题分析】
1. 登录到 Pod 1 所在节点，查看 flexvolume_disk.log 日志，显示磁盘挂载成功， lsblk 输出
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    253:0    0  500G  0 disk 
└─vda1 253:1    0  500G  0 part /
vdf    253:80   0   20G  0 disk /var/lib/origin/openshift.local.volumes/pods/84c78c3a-ae8c-11e9-9289-00163e10a746/volumes/alicloud~disk/d-2zeeo0hbl5sburw64rj5

2. 登录到 Pod 2 所在节点，查看flexvolume_disk.log 日志，**显示磁盘挂载成功(BUG)**， lsblk 输出
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    253:0    0  500G  0 disk 
└─vda1 253:1    0  500G  0 part /

3. 登录到阿里ecs云控制台，查看云盘挂载情况，显示磁盘当前是被挂载到 Pod 1 所在节点

【问题定位】
怀疑 flevolume 插件挂载磁盘，调用阿里云的相关接口，**这个接口没有检查当前磁盘已经被某个ecs实例挂载，并且error这次挂载请求**。

**Comment by ideapark** [comment]
@fredkan

**Comment by ideapark** [comment]
https://github.com/AliyunContainerService/flexvolume/blame/master/provider/disk/disk.go#L87

请确认这段代码是否逻辑上存在漏洞，例如：
1. 当前 disk 正在被 node1 使用
2. flexvolume attach disk 到 node2

这样处理 node1 上 的 disk 被强制解绑了 （BUG）

因该是，如果 node1 == node2 的情况下，代码的逻辑才是修复节点重启
               node1 != node2 的时候，是不能 detach 的，应该error提示disk正在被 node1使用，attach失败

**Comment by fredkan** [comment]
云盘不是共享盘，只能被一个节点挂载。
deployment方式使用云盘的话，只能是replica为1.

**Comment by fredkan** [comment]
> https://github.com/AliyunContainerService/flexvolume/blame/master/provider/disk/disk.go#L87
> 
> 请确认这段代码是否逻辑上存在漏洞，例如：
> 
> 1. 当前 disk 正在被 node1 使用
> 2. flexvolume attach disk 到 node2
> 
> 这样处理 node1 上 的 disk 被强制解绑了 （BUG）
> 
> 因该是，如果 node1 == node2 的情况下，代码的逻辑才是修复节点重启
> node1 != node2 的时候，是不能 detach 的，应该error提示disk正在被 node1使用，attach失败

目前设计云盘是争抢的，即：后面使用云盘的pod会把云盘抢走。
所以不能定义多个pod使用同一个云盘。

这样做的考虑：当一个pod被强制删除，或者卸载云盘失败时，新的pod启动，这时云盘需要抢夺过来。

**Comment by ideapark** [comment]
你说的这种场景针对这样的设计是有道理的。我想反馈下我们实践中的场景：

1. k8s 最大的一个能力是对 pod 的 scale up/down，我们实践过程中，
   很多同学使用 k8s 一上来就是去尝试把 replicas 改成>1 ，这些用户是没有
  有状态服务和无状态服务的概念的。

2. 以上操作实施在有磁盘的 pod上时，会导致 pod 被启动多个，相应的流量也会被导入到
    每个 Pod。当流量被导入到被 detach 磁盘的 Pod 时，oops！！！

3. 考虑到 k8s 这种环境下，云盘不应该是抢占的，毕竟节点down掉，或者完全不可恢复的
    场景是小概率事件，而我上面提到的场景是大概率事件。并且节点down掉后，我们 k8s
   管理员会尽快恢复 node。必要时还能手动 detach 云盘。

以上思考请你们参考，考虑到插件的设计抉择中。

**Comment by fredkan** [comment]
> 你说的这种场景针对这样的设计是有道理的。我想反馈下我们实践中的场景：
> 
> 1. k8s 最大的一个能力是对 pod 的 scale up/down，我们实践过程中，
>    很多同学使用 k8s 一上来就是去尝试把 replicas 改成>1 ，这些用户是没有
>    有状态服务和无状态服务的概念的。
> 2. 以上操作实施在有磁盘的 pod上时，会导致 pod 被启动多个，相应的流量也会被导入到
>    每个 Pod。当流量被导入到被 detach 磁盘的 Pod 时，oops！！！
> 3. 考虑到 k8s 这种环境下，云盘不应该是抢占的，毕竟节点down掉，或者完全不可恢复的
>    场景是小概率事件，而我上面提到的场景是大概率事件。并且节点down掉后，我们 k8s
>    管理员会尽快恢复 node。必要时还能手动 detach 云盘。
> 
> 以上思考请你们参考，考虑到插件的设计抉择中。

从产品运维、功能等角度出发，抢占式还是需要的。

1. 云盘是非共享存储，同一个pvc不能被多个pod使用是云盘使用的原则；
2. 您遇到的问题关键是，目前没有实现对多个pod使用一块云盘进行限制，导致第二个pod还是可以正常启动，并抢占了云盘。
3. 限制一个pvc被多个pod使用的原语是：ReadWriteOnce，但目前这个功能在k8s中没有实现，这个功能后续会进行改进。

**Comment by ideapark** [comment]
> 限制一个pvc被多个pod使用的原语是：ReadWriteOnce，但目前这个功能在k8s中没有实现，这个功能后续会进行改进。

同意，这也许才是问题比较合适的解决点。
